N8 a31 20
JYachelini/n-8-Alk-31-10 pull request #34
Opened 2022-11-08 15:01 UTC by AndresDP25

## TICKET

- [N8A31-20](https://julianyachelini.atlassian.net/browse/N8A31-20)

## Description
AS: Andres DP
I Want: create seeders of Users
To:

## Evidence:

### Happy Path
![image](https://user-images.githubusercontent.com/84631947/200599034-73e47564-30e2-4036-ad69-3fa9860c0523.png)

### Unhappy Path
(Put screenshots/video/gifs here)

2022-11-08 17:16 UTC, oliverajdev reviewed
faltaria agregar a los modelos el roleId para que puedas crear usuarios comunes y admins

2022-11-09 01:31 UTC, JYachelini requested changes

2022-11-09 01:31 UTC, JYachelini commented on database/seeders/20221108122917-create-users.js
> +  for (let i = 1; i <= 10; i++) {
Hay que crear 10 usuarios normales y 10 administradores. Tendrían que ser dos for hasta 10 y agregarle el roleId: 1

2022-11-09 01:32 UTC, JYachelini commented on database/seeders/20221108122917-create-users.js
> +  for (let i = 1; i <= 10; i++) {
El roleId solo para los administradores, a los usuarios normales ya se les asigna por defecto el rol de usuario

2022-11-09 16:52 UTC, JYachelini approved these changes

2022-11-09 16:52 UTC, merged