<web-server> (29) endpoint crear usuario
JYachelini/n-8-Alk-31-10 pull request #5
Opened 2022-11-02 16:03 UTC by oliverajdev

## TICKET

- [N8A31-29][(INSERT TICKET LINK HERE)](https://julianyachelini.atlassian.net/browse/N8A31-29)

## Description

Se debe hacer una petición POST /users

Se verificará que la petición contenga los campos firstane, lastname, email y password

Deberá encriptar la contraseña en la base de datos con la libreria 

bcrypt- Deberá validar que el email no se encuentre registrado. Notificar en caso que ya exista

falta el middelware para las validaciones y en los models falta agregar passwords en users

El endpoint devolverá todos los datos del usuario
AS: Jeronimo Olivera
I Want:  crear endpoint para crear usuario
To:

## Evidence:
![chrome_uOylHkir8a](https://user-images.githubusercontent.com/86572008/199539688-9850036a-5576-4001-b2f6-f10c96cbb4b0.png)

### Happy Path

### Unhappy Path
(Put screenshots/video/gifs here)

2022-11-02 16:22 UTC, JYachelini requested changes
hay q cambiar un par de cosas, también elimina el package-lock del commit y pullea la rama dev para que el .gitignore se te actualize. Package-lock esta tirando muchos conflictos pq se estan instalando dependencias

2022-11-02 16:22 UTC, JYachelini commented on database/models/role.js
> +        deletedAt: {
deletedAt tiene que estar como el de arriba
deletedAt: DataTypes.DATE
deletedAt:{} se hace en el archivo migrations

2022-11-02 16:22 UTC, JYachelini commented on docker-compose.yml
> -version: '2.4'
No borres este archivo porque es necesario para los que usamos docker

2022-11-02 16:22 UTC, JYachelini commented on controllers/users.js
> +  create: catchAsync(async (req, res, next) => {
esta funcion tiene que ir en el module.exports de arriba, como esta el get de ejemplo
module.exports = {
  create: catchAsync(async (req, res, next) => {
      try {
      var {fistName,lastName,email,password} = req.body

      password = bcrypt.hashSync(password,10)

      const response = await User.create({
        fistName,
        lastName,
        email,
        password
      })
      endpointResponse({
        res,
        message:'success',
        body: response
      })
    } catch(error) {
      const httpError = createHttpError(
        error.statusCode,
        `[Error retrieving users] - [index - GET]: ${error.message}`,
      )
      next(httpError)
    }
  })
  }),

2022-11-02 16:53 UTC, JYachelini requested changes

2022-11-02 16:53 UTC, JYachelini commented on .vscode/settings.json
> +{
tmb saca el settings.json del commit para q no reemplace la config que hay en dev

2022-11-02 17:06 UTC, oliverajdev commented on database/models/role.js
> +        deletedAt: {
listo

2022-11-02 17:07 UTC, oliverajdev commented on docker-compose.yml
> -version: '2.4'
listo

2022-11-02 17:07 UTC, oliverajdev commented on .vscode/settings.json
> +{
listo

2022-11-02 17:14 UTC, JYachelini requested changes

2022-11-02 17:14 UTC, JYachelini commented on app.js
> +	.sync({ force:true })
el force: true no es buena practica que este porque siempre va a estar forzando a la base de datos. Si necesitas reiniciar la base de datos para hacer algunos cambios agrega el force:true pero no lo mantengas para siempre
Mantene el logging false para que no se llene la consola de scripts

2022-11-02 17:14 UTC, JYachelini commented on controllers/users.js
> +      var {fistName,lastName,email,password} = req.body
cambia var por const, var esta muy en desuso y puede generar problemas

2022-11-02 17:14 UTC, JYachelini commented on package.json
> +<<<<<<< HEAD
soluciona el conflicto que hay en package.json

2022-11-02 17:43 UTC, oliverajdev commented on app.js
> +	.sync({ force:true })
listo

2022-11-02 17:43 UTC, oliverajdev commented on package.json
> +<<<<<<< HEAD
listo

2022-11-02 17:44 UTC, oliverajdev commented on controllers/users.js
> +      var {fistName,lastName,email,password} = req.body
no es necesario en este caso , si pongo const no puedo modificar el password en mi codigo. uso let

2022-11-02 17:57 UTC, JYachelini commented on controllers/users.js
> +      var {fistName,lastName,email,password} = req.body
let esta bien entonces

2022-11-03 13:42 UTC, JYachelini requested changes

2022-11-03 13:42 UTC, JYachelini commented on controllers/users.js
Verirficación de que el email no exista, ya que el email tiene que se unico para cada usuario
ejemplo:
`const findUser = await User.findOne({ where: { email } })`
`if(findUser) throw new Error(...)`

2022-11-03 14:07 UTC, JYachelini approved these changes

2022-11-03 14:07 UTC, merged