N8 a31 35 Endpoint-for-delete-categories.
JYachelini/n-8-Alk-31-10 pull request #54
Opened 2022-11-10 22:05 UTC by Bloodycaps

## TICKET
N8A31-35

## Description
It must validate the existence based on the id sent by parameter. If it exists, remove it.

## Evidence:

### Happy Path
![image](https://user-images.githubusercontent.com/38762360/201214392-8b734141-ba97-4716-ba8d-c74928772307.png)
sent 

### Unhappy Path
![image](https://user-images.githubusercontent.com/38762360/201214092-6fd392e4-14b0-4daa-8d8c-345b6c1e7918.png)

2022-11-10 22:25 UTC, JYachelini requested changes

2022-11-10 22:25 UTC, JYachelini commented on controllers/categories.controller.js
> +        code: 204,
el código http tendría que ser 200 y si podes agregale un mensajito de que la categoria fue borrada

2022-11-10 22:56 UTC, Bloodycaps commented on controllers/categories.controller.js
> +        code: 204,
ya se cambio el codigo http de respuesta y el mesaje

2022-11-10 23:42 UTC, Bloodycaps commented
ya se cambio el codigo http de respuesta y el mesaje

2022-11-11 01:22 UTC, JYachelini approved these changes

2022-11-11 01:22 UTC, merged